# Generated by Django 4.2.1 on 2023-11-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrelation',
            name='userName',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
    ]
