# Generated by Django 4.2.1 on 2023-12-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
