# Generated by Django 4.2.1 on 2024-01-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0002_alter_product_image'),
        ('Base', '0003_alter_userproducts_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StoreApp.product'),
        ),
    ]
